name: Publish Package to npmjs.com

on:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/npm-build.yml

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: lib
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
