name: Build and test npm Package

on:
  workflow_call:
      
  push:
    branches:
      - 'master'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - uses: actions/upload-artifact@v3
        name: artifact
        with:
          retention-days: 1
          path: |
            lib
            !lib/tests
