name: upgrade Packages

on:
  schedule:
    - cron: '0 12 1 * *'

jobs:
  upgrade-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm upgrade
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
